# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8082
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.cumt: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  datasource:
    username: root
    password: '021125'
    url: jdbc:mysql://localhost:3306/bank-vue?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#josn解析
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#配置为开发环境
  profiles:
    active: druid
#mvc配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      load-on-startup: 1
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
    host: localhost
    port: 6379


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true


mybatis:
  typeAliasesPackage: com.cumt.bankapp.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
jwt:
  # ??jwt??????????
  admin-secret-key: cumt
  # ??jwt????
  admin-ttl: 7200000
  # ?????????????
  admin-token-name: token
  # jwt????
  current-user: current-user
mica:
  xss:
    enabled: true
    path-patterns: /**
# flowable相关表
flowable:
  # true 会对数据库中所有表进行更新操作。如果表不存在，则自动创建(建议开发时使用)
  database-schema-update: false
  # 关闭定时任务JOB
  async-executor-activate: false
